version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: web
    ports:
      - 8080:80
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  products.queue:
    image: ${DOCKER_REGISTRY-}productsqueue
    build:
      context: .
      dockerfile: src/Services/Products.Queue/Dockerfile
    container_name: productsqueue
    depends_on:
      - rabbitmq
      - nosql.data

  products.database:
    image: ${DOCKER_REGISTRY-}productsdatabase
    build:
      context: .
      dockerfile: src/Services/Products.Database/Dockerfile
    container_name: productsdatabase
    depends_on:
      - rabbitmq
      - mongo.data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq

  nosql.data:
    image: redis 
    container_name: redis

  mongo.data:
    image: mongo:latest
    environment:
        - MONGO_INITDB_DATABASE=productsdb
        - MONGO_INITDB_ROOT_USERNAME=demo
        - MONGO_INITDB_ROOT_PASSWORD=demo123
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGODB_USER=demo
        - MONGODB_PASS=demo123
    ports:
        - 27017:27017
    container_name: mongodb
