version: '3.4'

networks:
  demonet:

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    container_name: web
    ports:
      - 8080:80
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - demonet

  products.queue:
    image: ${DOCKER_REGISTRY-}productsqueue
    build:
      context: .
      dockerfile: src/Services/Products.Queue/Dockerfile
    container_name: productsqueue
    depends_on:
      - rabbitmq
      - nosql.data
    networks:
      - demonet

  products.database:
    image: ${DOCKER_REGISTRY-}productsdatabase
    build:
      context: .
      dockerfile: src/Services/Products.Database/Dockerfile
    container_name: productsdatabase
    depends_on:
      - rabbitmq
      - mongo.data
    networks:
      - demonet

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
      - 5672:5672
    container_name: rabbitmq
    networks:
      - demonet

  nosql.data:
    image: redis 
    container_name: redis
    networks:
      - demonet

  mongo.data:
    image: mongo:latest
    environment:
        - MONGO_INITDB_DATABASE=productsdb
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin123
        - MONGO_DATA_DIR=/data/db
        - MONGO_LOG_DIR=/dev/null
        - MONGODB_USER=demo
        - MONGODB_PASS=demo123
    ports:
        - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    container_name: mongodb
    networks:
      - demonet
